### ISSUE TITLE
isPasswd() method has been removed in PS 8 / make this module PS 8+ compatible

### ISSUE THREAD

**Issue by marob** [binshops/prestashop-rest#40]
PS 8 removed `isPasswd()` method: https://github.com/PrestaShop/PrestaShop/pull/26315

This method is used in this module, for example:
https://github.com/binshops/prestashop-rest/blob/3f2f7f454397333afd5b420a6c7fb0036272185d/controllers/front/register.php#L34

This module should be updated to be compatible with PS 8.

**Comment by samberrry** [comment]
This is the demo version with less maintenance and support, the official version (https://addons.prestashop.com/en/website-performance/52062-rest-api-pro-for-front-applications-integrations.html#reviews) is already fully compatible with PS 8 and fixed the issues.   

register, login, createorder (create order in one request in Pro version) affected by this `isPasswd()` which has changed in the old version v4.4.0. However, I will bring this update to the demo version too.

thanks.

**Comment by marob** [comment]
@samberrry

I've had difficulties to tell what's the differences between free and paid version. But, [your website](https://www.binshops.com/prestashop-api) says:

> Totally free without any restriction

So I suppose that's not true.
Could you make it clear what's in the free version and what's not?

Thx

**Comment by samberrry** [comment]
@marob 
I think it needs a small change, because the phrase goes back to the days that this page was using for the free version. Currently, we are using a single landing page for both versions. 
but the demo version is totally free without restriction to change, and use..

the demo version is mainly intended for testing and helping others to contribute to the PrestaShop ecosystem to build front-end applications and grow the space. So, it helps developers to test and work with a front-ready API.

Most of the development work is being done on the official version which and it includes the essential functionalities and is recommended for production: https://addons.prestashop.com/en/website-performance/52062-rest-api-pro-for-front-applications-integrations.html
also the official version includes support and a very helpful manual doc for API which helps building front-end apps. More features have been mentioned in our website too. 

However, we will keep the the demo version working, and we will trying to keep the same data structure. 

Thanks
